### ISSUE TITLE
Option to automatically lock zoomed images to center of the page

### ISSUE THREAD

**Issue by icp1994** [extesy/hoverzoom#1216]
**Is your feature request related to a problem? Please describe.**
For my use cases of hoverzoom, I almost always want to lock the hovered images for pan/zoom.

**Describe the solution you'd like**
It would be nice to have an option to auto-lock zoomed images rather than having to use an additional hotkey. Especially since I use `Ctrl` modifier for `Activate HoverZoom+`, using it with another key interferes with browser default hotkeys.

**Describe alternatives you've considered**
I have briefly searched for workarounds to lock without using hotkey.

**Additional context**
N/A

**Comment by extesy** [comment]
@icp1994 You can use right click to do that:
![image](https://github.com/extesy/hoverzoom/assets/65872/357de177-a52f-482b-80e5-075e6e8edf85)

**Comment by icp1994** [comment]
True, that's what I used at first. But it also triggered browser's context menu (open in new tab, open in new window, save as etc) which was a bit annoying often times.

I think even without implementing this feature, if you allow `ALT` as an action key that will solve my problem since I don't have browser shortcuts that would conflict with Alt modifier.

**Comment by TraceGroot** [comment]
I have to agree with this issue.  It's a royal pain to have to hold down the enable key and/or have to separately press the L key in order to get an image to lock in place.

This is a very easy item to implement via a simple configuration setting.  "Automatically Lock when Activating" - On/Off.

This one issue is what keeps me using Imagus instead of HoverZoom+.

**Comment by extesy** [comment]
Fixed by 1d85309a0f2473bbe226cf524dc2e7ab25738e99, will be available in the next release.
