### ISSUE TITLE
Why is HoverZoom suddenly asking for the "Manage your downloads" permission?

### ISSUE THREAD

**Issue by stravant** [extesy/hoverzoom#362]
Please explain? I don't see any explanation anywhere in the information for the extension.

**Comment by germaloney11** [comment]
Would also like to know answer for this please.

**Comment by parseHex** [comment]
I'm not a dev on this but I was curious too, took a quick look and saw that the [latest commit](https://github.com/extesy/hoverzoom/commit/deac0fe6289b77eb62efacf8b875088448201aa9) is what added this permission.

From the commit message, it looks like saving images was broken (never run into it myself but I don't save images), so they changed the way images are downloaded.

Before, the image would be downloaded in a kind of hacky way because JavaScript doesn't have a good official way of downloading files. Now, the extension uses Chrome's API to download the image, which is why it needs the permission.

Again, I'm not a dev on this project so somebody else probably can explain it better. It looks all good to me, I'll be letting Chrome re-enable the extension.

**Comment by Sushubh** [comment]
This is the bug report that was closed today. 
https://github.com/extesy/hoverzoom/issues/357

**Comment by JoshuaaMichael** [comment]
If this new permission is certainly needed, the description of the extension will need to be updated on the Chrome Web Store.
"The only permission it needs is to access data on all websites (to extract full images), and *optional* permissions to access browser history or get tab urls for per-site configuration."

**Comment by extesy** [comment]
Already answered in #361.
