### ISSUE TITLE
Please add support for redgifs.com

### ISSUE THREAD

**Issue by Zenivo** [extesy/hoverzoom#508]
Gfycat NSFW content has migrated to redgifs.com, but this is not supported by the plugin.

**Comment by Eiion** [comment]
Came here to suggest the same, considering regifs.com the new place for basically every nsfw content that typically was posted on the very popular gfycat.com. (It's gfycat's own new nsfw website.)

**Comment by Eiion** [comment]
@extesy You've closed the issue and it seems that you've added the plugin. I've tried something similar locally but that didn't work.
Not sure if I'm on the newest version yet (I'm on 1.0.143) since the extension isn't listed on the store anymore (https://chrome.google.com/webstore/detail/pccckmaobkjjboncdfnnofkonhgpceea only gives me a 404 error) - but it's certainly not working for me right now.

Any info on why the extension went missing from the store?

**Comment by extesy** [comment]
@Eiion Please look at #512.

**Comment by Eiion** [comment]
Oh dear... 🙄
Ok. I've replied to that other post.
But, for now, what would I have to do to add the plugin manually? I can create a script in the extensions folder and add the plugin by hand, but would that be all? When playing around with this before the plugin did not show up on the options page of the extension... are there other files that need to be modified for the plugin to show up in the options menu? (I honestly don't need it on the option's plugins page - but assuming this is needed for it to work is why I'm asking.)

**Comment by Eiion** [comment]
@extesy Since the extension is back in the store I went back to that version (instead of the manually installed one via dev tools). Unfortunately in the store's version redgifs is (still?) not working. Is that still the pre-update pre-store-issues version or has there been plugins removed?

**Comment by Eiion** [comment]
@extesy I saw that you've made a change, applied it manually but that didn't help. I've once again got the current zip, unpacked and installed in via dev mode - again, the plugin is still not working. While before it worked for some, now it actually works for none of the gifs hosted on redgifs that I could find on reddit.

**Comment by Eiion** [comment]
Today I've come across a post where - after clicking on the gfycat link in the reddit app - I landed on "gifdeliverynetwork.com" where the gif hat a watermark saying "REDGIFS This GIF is hosted by RedGIFs"

It appears to me that gfycat is messing around with how they host the content and moved on to pushing the NSFW gifs to "gifdeliverynetwork" instead of to redgifs... no idea what's going on with that.
