### ISSUE TITLE
Facebook Position Photo

### ISSUE THREAD

**Issue by Djspaceg** [extesy/hoverzoom#78]
This may or may not be the right place to report this, but my only issue with Hover Zoom+ is that it's really challenging on Facebook to reposition cover images (your own profile or an event). I tried an exclude/blacklist entry for my "Edit my profile" page, but it didn't seem to parse the dirs/paths from the URL, and only matched on the domain –all of Facebook.

There may be two different solutions here.

1. Have a key assigned which when held disables Hover Zoom+
2. Look into and possibly mend blacklisting parts of domains, not just domains. The docs seemed to indicate this was possible or already implemented, but I didn't have any luck. Could you provide an example of what should work?

Thanks in advance

**Comment by extesy** [comment]
Thanks for reporting this issue, @Djspaceg.

1. This option already exists. See second action key in the extension options.
2. I don't have any example right now, but I'll find out and follow up later.

**Comment by extesy** [comment]
@Djspaceg Hoverzoom exclusions block based on url of the host page, not url of the image. So for example for https://www.facebook.com/blake page if you want to disable hoverzoom there, you can add `facebook.com/blake` into exclusion. But this will disable zooming for all images on that page, not just cover image. There's no way to disable zooming of only cover photo because it's the image that is served from the sample place as all other images.
