### ISSUE TITLE
disable on site shadertoy.com → still freeze the site display.

### ISSUE THREAD

**Issue by FabriceNeyret** [extesy/hoverzoom#902]
The bug occurs on chrome & chromium on URL https://www.shadertoy.com/profile/?show=shaders  ( which is valid only if you have an account + contents on the shadertoy website ) . On this page you see the long list of your content + a small image for each, but with the extension ON, this page get frozen with no content but the header.

The solution is supposed to simply blacklist shadertoy.com  from the extension parameters, but it doesn't work:
I have specifically to set (in chrome) "allow extension to read and change data" = "on specific site" ( too bad we cannot une a blacklist here ) then clear cache and cookies (both step necessary ) for the list get displayed again.

**Comment by GrosPoulet** [comment]
<séquence émotion>Shadertoy! The place where mathematics give birth to Art :heart_eyes: My favorite: https://www.shadertoy.com/view/XsfGD4</séquence émotion>
Too bad HZ+ & Shadertoy do not get along well...

=> Can you precise your Chrome version, OS & HZ+ release ?

2 remarks:

- blacklisting "shadertoy.com" works fine for me. Adding is not enough, make sure you saved after adding.

- back in 2015, i made some -miserable- attemp to shader coding (only 4 shaders).
When i display my shaders list (https://www.shadertoy.com/profile/?show=shaders), i observe no freeze:

![profile](https://user-images.githubusercontent.com/23529041/161378210-e8475aad-1ac5-46f6-b992-27bd9b58e69a.png)

So freeze might only occur with high numbers of shaders, like on your own profile.
=> Can you please enable debug (Options -> Advanced -> Troubleshooting), then open Chrome console & see if we can get some additional info ?

I guess this issue is related to #890: addition of many nodes to DOM triggers many "DOMNodeInserted" events (catched by HZ+) & freezes browser. 
We need to rework this part.

**Comment by GrosPoulet** [comment]
<séquence émotion>Shadertoy! The place where mathematics give birth to Art :heart_eyes: 
My favorite: https://www.shadertoy.com/view/XsfGD4</séquence émotion>
Too bad HZ+ & Shadertoy do not get along well...

=> Can you precise your Chrome version, OS & HZ+ release ?

2 remarks:

- blacklisting "shadertoy.com" works fine for me. Adding is not enough, make sure you saved after adding.

- back in 2015, i made some -miserable- attemp to shader coding (only 4 shaders).
When i display my shaders list (https://www.shadertoy.com/profile/?show=shaders), i observe no freeze:
![profile](https://user-images.githubusercontent.com/23529041/161378489-7a85570e-3031-4127-9563-94ef404e5459.png)



So freeze might only occur with high numbers of shaders, like on your own profile.
=> Can you please enable debug (Options -> Advanced -> Troubleshooting), then open Chrome console & see if we can get some additional info ?

I guess this issue is related to #890: addition of many nodes to DOM triggers many "DOMNodeInserted" events (catched by HZ+) & freezes browser. 
We need to rework this part.
