### ISSUE TITLE
Add support for : https://us.shein.com/

### ISSUE THREAD

**Issue by ijustliketoread** [extesy/hoverzoom#906]
**What is the URL of the website**
https://us.shein.com/

**Why we should add support for the website?**
Online shopping - increase image size.

Video showing Hover Zoom+ currently does not function on Shein:
https://www.loom.com/share/003b863fe663489e83889463177502e1

**Comment by GrosPoulet** [comment]
Hi @ijustliketoread
I added a new plug-in for shein.com (#907)
Since i never bought anything from them, i could not test the "order" page but it should work.
It'll be available in next release of HZ+ by @extesy (1.0.190)

![shein](https://user-images.githubusercontent.com/23529041/162211736-ddbe91ee-547b-4eb7-9835-0d6225fc2426.jpg)

**Comment by extesy** [comment]
Fixed by #907. Thank you, @GrosPoulet!

**Comment by ijustliketoread** [comment]
Thank you @GrosPoulet!! 😁 🥰
